### ISSUE TITLE
error running extension !

### ISSUE THREAD

**Issue by kotaxyz** [russellpwirtz/textgen_websearch#1]
thanks for this awesome extention , i get error when running it ,i use latest repo of oba

User
Starting web search! Original input string:
google: what is the best godfather movie?
Performing web search: what is the best godfather movie?
Found links from web search: ['https://www.cbr.com/every-godfather-movie-ranked-best-worst/', 'https://www.imdb.com/list/ls069897701/', 'https://www.reddit.com/r/movies/comments/i3umct/which_one_is_your_favorite_the_godfather_or_the/', 'https://www.quora.com/In-your-opinion-how-would-you-rank-the-Godfather-movies-in-order', 'https://www.giantfreakinrobot.com/ent/al-pacino-best-godfather-movie.html', 'https://www.thegreatestfilms.com/Film/1972/The-Godfather', 'https://www.bupipedream.com/ac/125812/fiftieth-year-of-the-godfather-a-comprehensive-ranking/', 'https://www.youtube.com/watch?v=vx3lElZTCtg']
Calling url: https://www.cbr.com/every-godfather-movie-ranked-best-worst/
Traceback (most recent call last):
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "I:\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "I:\text-generation-webui\modules\chat.py", line 342, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "I:\text-generation-webui\modules\chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "I:\text-generation-webui\modules\chat.py", line 217, in chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\extensions\textgen_websearch\script.py", line 102, in input_modifier
    token_count = get_token_count(web_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\text-generation-webui\extensions\textgen_websearch\script.py", line 122, in get_token_count
    return int(shared.tokenizer.encode(str(text)).shape[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'

**Comment by russellpwirtz** [comment]
@kotaxyz Thanks! Please try again now - I saw the same thing after updating to latest webgen, should be fixed now.
